### ISSUE TITLE
れお injection

### ISSUE THREAD

**Issue by defaultcf** [uehara1414/kirakira-name-generator#3]
"れお"と入力したら500返ってきた。
平仮名の入力が原因と思われる。

**Comment by uehara1414** [comment]
"とまと"で問題なく動いたからひらがなの入力が原因ではない。

**Comment by uehara1414** [comment]
解決しました。
Wikipedia に存在しない言葉が入力された場合、まず Wikipedia 内で検索をかけて最初に提示された記事からキラキラネームを生成するようにしました。

ちなみに、「れお」で検索をかけると「かなでれおん」というグラビアアイドルから生成します。

**Comment by defaultcf** [comment]
解決して良かったです。

かなでれおん可愛い。
